//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMapperConsoleDEMO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Name { get; set; }
        public string Attribute { get; set; }
        public int Price { get; set; }
        public Nullable<int> PromotionPrice { get; set; }
        public int LimitCount { get; set; }
        public string SpecNote { get; set; }
        public string Description { get; set; }
        public System.DateTime ActiveSDate { get; set; }
        public System.DateTime ActiveEDate { get; set; }
        public bool ActiveEnable { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> ModifiedOnUtc { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
